"""FormSchema intermediate representation + fingerprints (pure, zero I/O).

The IR is the single data structure every stage shares (spec §6.3). Options are
enumerated LAZILY (the LAZY sentinel) — never at parse (invariant 4). field_fp
is the primary cache key and is built to survive id/class churn (invariant 10)
by dropping auto-generated tokens via healing._looks_autogenerated."""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Any

from applypilot.apply.healing import _looks_autogenerated


class _Lazy:
    """Singleton sentinel: 'options not yet enumerated' (distinct from [] =
    'enumerated, none'). Identity-checked with `is ir.LAZY`."""
    __slots__ = ()
    def __repr__(self) -> str:  # noqa: D401
        return "LAZY"


LAZY = _Lazy()


class WidgetKind:
    ALL = (
        "text", "textarea", "native_select", "react_select", "radio_group",
        "checkbox", "file", "date", "phone_intl", "typeahead_location",
        "segmented_button", "unknown",
    )


# Canary semantic keys: resolve ONLY from exact profile paths / typed policy
# defaults — never Operator, never answer bank, never fuzzy (spec §10.3).
_CANARY_KEYS = {"work_auth", "sponsorship", "citizenship", "salary", "address", "dob"}


def is_canary_key(semantic_key: str | None) -> bool:
    if not semantic_key:
        return False
    root = semantic_key.split(".", 1)[0]
    return root in _CANARY_KEYS or semantic_key in _CANARY_KEYS


@dataclass(frozen=True)
class Widget:
    kind: str = "unknown"
    framework_hints: tuple[str, ...] = ()


@dataclass
class Field:
    field_id: str                       # DOM id/name AT PARSE (may be autogen)
    frame_path: tuple[str, ...]         # frame chain, () = top document
    label_text: str
    question_text: str
    semantic_key: str | None            # taxonomy below, or custom.* / None
    widget: Widget
    options: Any = LAZY                 # LAZY until a driver enumerates them
    required: bool = False
    char_limit: int | None = None
    depends_on: str | None = None       # field_id this field is conditional on
    locator_spec: dict[str, Any] = field(default_factory=dict)  # -> ElementSpec (Task 5)


@dataclass
class Step:
    index: int
    fields: list[Field] = field(default_factory=list)
    advance_control: dict[str, Any] | None = None   # locator_spec of Next/Submit
    terminal: bool = False


def _stable_token(tok: str | None) -> str:
    """Return the token only if it is a stable, human-authored id/class token;
    auto-generated tokens (id/class churn) collapse to '' so they never anchor a
    fingerprint (invariant 10)."""
    return "" if _looks_autogenerated(tok) else (tok or "")


def _options_shape(f: "Field") -> str:
    """Shape, not values: LAZY -> 'lazy'; concrete -> count only (no values leak
    into a fingerprint input)."""
    if f.options is LAZY:
        return "lazy"
    opts = [str(o).strip() for o in (f.options or []) if str(o).strip()]
    return f"n={len(opts)}"


def field_fp(f: "Field") -> str:
    """Primary cache key: label + widget kind + options-shape + semantic_key,
    with id/class churn stripped. Deliberately EXCLUDES the raw field_id so the
    fp survives ATS id/class churn (invariant 10: the key is label + widget kind
    + options-shape [+ semantic_key]). The field_id is a per-render DOM handle,
    not identity — including it (even filtered through _looks_autogenerated,
    which is deliberately conservative and misses some autogen shapes) would let
    id churn move the fp, which is exactly the failure invariant 10 forbids."""
    payload = "|".join([
        (f.label_text or "").strip().lower(),
        (f.question_text or "").strip().lower(),
        f.widget.kind,
        _options_shape(f),
        f.semantic_key or "",
    ])
    return hashlib.sha1(payload.encode("utf-8")).hexdigest()


def question_fp(f: "Field") -> str:
    """Custom-question identity (frame + label + question text + widget)."""
    payload = "|".join([
        "/".join(f.frame_path),
        (f.label_text or "").strip().lower(),
        (f.question_text or "").strip().lower(),
        f.widget.kind,
    ])
    return hashlib.sha1(payload.encode("utf-8")).hexdigest()


def _is_standard(f: "Field") -> bool:
    return bool(f.semantic_key) and not f.semantic_key.startswith("custom.")


@dataclass
class FormSchema:
    ats: str
    company: str
    url: str
    steps: list[Step] = field(default_factory=list)

    def _all_fields(self) -> list[Field]:
        return [fld for s in self.steps for fld in s.fields]

    def template_fp(self) -> str:
        """Step structure + standard (semantic-keyed) fields — shared across
        companies on the same ATS template (spec §6.3)."""
        parts = []
        for s in self.steps:
            std = sorted(field_fp(f) for f in s.fields if _is_standard(f))
            parts.append(f"step{s.index}:{'+'.join(std)}:term={int(s.terminal)}")
        payload = json.dumps({"ats": self.ats, "steps": parts}, sort_keys=True)
        return hashlib.sha1(payload.encode("utf-8")).hexdigest()

    def questions_fp(self) -> str:
        """The custom-question delta — differs job-to-job on the same template."""
        cust = sorted(question_fp(f) for f in self._all_fields()
                      if f.semantic_key and f.semantic_key.startswith("custom."))
        return hashlib.sha1("+".join(cust).encode("utf-8")).hexdigest()
