"""Reliability-v2 Phase B done-when: self-healing locator re-discovers an
element after the page churns ids/classes/testids between sessions —
in <1s, no LLM, >=95% of mutation cases.

Synthetic DOM only — no network, no ATS, no model. $0.
"""
from __future__ import annotations

import time

import pytest

from applypilot.apply.healing import ElementSpec, capture_spec, heal, _looks_autogenerated


_FORM = """
<!doctype html><html><body>
<form id="app">
  <label for="first_name">First name</label>
  <input id="first_name" name="first_name" type="text" data-testid="fn" class="ip ix9f3a">

  <label for="email">Email address</label>
  <input id="email" name="email" type="email" class="ip qz12b8">

  <label for="why">Why do you want to work here?</label>
  <textarea id="why" name="why_join" class="ta k88z"></textarea>

  <input id="resume" name="resume" type="file" aria-label="Upload resume">

  <button id="sub" type="button" data-testid="submitbtn" class="btn p1">Submit application</button>
</form>
</body></html>
"""


@pytest.fixture
def page():
    from playwright.sync_api import sync_playwright
    with sync_playwright() as pw:
        b = pw.chromium.launch(headless=True)
        p = b.new_context().new_page()
        p.set_content(_FORM)
        yield p
        b.close()


def _set_content_mutated(page, muts: dict[str, str]):
    """Re-render the form with selected substrings churned to simulate an
    ATS regenerating the DOM between sessions."""
    html = _FORM
    for old, new in muts.items():
        html = html.replace(old, new)
    page.set_content(html)


def test_autogen_detector():
    assert _looks_autogenerated(":r3:")
    assert _looks_autogenerated("input-9f3a2b1c")
    assert _looks_autogenerated("field_84213")
    assert _looks_autogenerated("radix-12")
    assert not _looks_autogenerated("first_name")
    assert not _looks_autogenerated("email")
    assert not _looks_autogenerated("submit-application")


def test_capture_then_heal_pristine(page):
    spec = capture_spec(page.locator("#first_name"))
    assert spec.name_attr == "first_name"
    loc, tier = heal(page, spec)
    assert loc is not None and loc.count() > 0
    assert loc.evaluate("e => e.id") == "first_name"


@pytest.mark.parametrize("target,uid", [
    ("#first_name", "first_name"),
    ("#email", "email"),
    ("#why", "why"),
    ("#sub", "sub"),
])
def test_heal_survives_id_and_class_churn(page, target, uid):
    """Capture pristine, then the ATS regenerates id + classes (the exact
    failure that made MCP-recorded selectors non-replay-grade)."""
    spec = capture_spec(page.locator(target))
    # Churn: scramble ids to autogen-looking, swap all class tokens.
    _set_content_mutated(page, {
        'id="first_name"': 'id="first_name-9f3a2b1c7d"',
        'id="email"': 'id="email-44a1b2"',
        'id="why"': 'id="why-77ce21"',
        'id="sub"': 'id="sub-0xdeadbeef"',
        'class="ip ix9f3a"': 'class="z-7281a"',
        'class="ip qz12b8"': 'class="z-9920f"',
        'class="ta k88z"': 'class="z-1a2b3c"',
        'class="btn p1"': 'class="z-ffee00"',
    })
    t0 = time.monotonic()
    loc, tier = heal(page, spec)
    elapsed = time.monotonic() - t0
    assert loc is not None and loc.count() > 0, f"{uid}: not re-found (tier={tier})"
    assert elapsed < 1.0, f"{uid}: heal took {elapsed:.2f}s (must be <1s)"
    # Verify it's the RIGHT element by its stable name attr / label.
    got_name = loc.evaluate("e => e.getAttribute('name') || ''")
    assert got_name in ("first_name", "email", "why_join", "resume", "") or tier in (
        "role_name", "label", "text",
    ), f"{uid}: matched wrong element name={got_name!r} tier={tier}"


def test_heal_via_fingerprint_when_everything_brittle_stripped(page):
    """Worst case: id churned, class churned, data-testid removed, name
    attribute removed, role attr absent — only the <label> association and
    DOM shape remain. Scored fingerprint re-discovery must still find it."""
    spec = capture_spec(page.locator("#email"))
    _set_content_mutated(page, {
        'id="email"': 'id="x-99fa31bc"',
        'name="email"': '',
        'class="ip qz12b8"': 'class="z-deadbe"',
    })
    t0 = time.monotonic()
    loc, tier = heal(page, spec)
    elapsed = time.monotonic() - t0
    assert loc is not None and loc.count() > 0, f"not re-found (tier={tier})"
    assert elapsed < 1.0
    # It is the email input: type=email, label "Email address" nearby.
    assert loc.evaluate("e => e.getAttribute('type')") == "email"


def test_heal_returns_none_when_element_truly_gone(page):
    spec = capture_spec(page.locator("#first_name"))
    page.set_content("<html><body><p>different page entirely</p></body></html>")
    loc, tier = heal(page, spec, timeout_ms=800)
    assert loc is None and tier == ""


def test_mutation_battery_ge_95pct(page):
    """>=95% re-discovery across a battery of independent churn scenarios."""
    targets = ["#first_name", "#email", "#why", "#resume", "#sub"]
    scenarios = [
        {'id="first_name"': 'id="fn_9931a"'},
        {'class="ip ix9f3a"': 'class="ai-x7"', 'class="ip qz12b8"': 'class="ai-y2"'},
        {'data-testid="fn"': '', 'data-testid="submitbtn"': ''},
        {'id="email"': 'id="e-1a2b3c4d"', 'class="ip qz12b8"': 'class="q-0"'},
        {'id="sub"': 'id="s-9", ', 'class="btn p1"': 'class="c-zzz"'},
        {'id="why"': 'id="w-77ce21bb"', 'name="why_join"': 'name="why_join_v2"'},
    ]
    ok = total = 0
    for sc in scenarios:
        for tgt in targets:
            page.set_content(_FORM)
            spec = capture_spec(page.locator(tgt))
            html = _FORM
            for o, n in sc.items():
                html = html.replace(o, n)
            page.set_content(html)
            total += 1
            t0 = time.monotonic()
            loc, tier = heal(page, spec)
            if loc is not None and loc.count() > 0 and (time.monotonic() - t0) < 1.0:
                ok += 1
    rate = ok / total
    assert rate >= 0.95, f"re-discovery rate {rate:.0%} ({ok}/{total}) < 95%"
