"""Reliability-v2 Phase B: self-healing locator core (zero LLM).

Implements the 2026 "Zero-Cost Self-Healing via DOM Accessibility Tree"
approach: a priority-ranked locator hierarchy plus a multi-signal element
fingerprint with scored re-discovery. When a recorded selector breaks
(ATS regenerates ids/classes between sessions — the exact thing that made
MCP-recorded skills non-replay-grade), we re-find the element by SEMANTICS
(role / accessible name / label / nearby text / attributes), not by the
brittle id that changed.

No LLM, no network. `heal()` returns a Playwright Locator + the tier that
matched, in well under a second.

Locator priority (most stable → least):
  1. role + accessible name      (W3C ARIA — survives styling/id churn)
  2. label text                  (form fields: <label for> / wrapping)
  3. data-testid                 (intentionally stable test hooks)
  4. stable id                   (skipped if it looks auto-generated)
  5. name attribute              (form posts depend on it → stable)
  6. placeholder
  7. aria-label
  8. stable-looking css class fragment
  9. exact visible text
 10. SCORED FINGERPRINT re-discovery (scan candidates, score vs the
     captured multi-signal fingerprint, take the best over threshold)
"""
from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from playwright.sync_api import Locator, Page

# An id/class token is "auto-generated" (unstable) if it has long digit runs,
# hashy hex, or framework churn prefixes. We refuse to anchor on these.
_AUTOGEN_RE = re.compile(
    r"(:r[0-9a-z]+:|[-_][0-9a-f]{6,}|\d{4,}|^ember\d+|^ext-gen\d+|^mui-\d+|^react-aria\d+|^radix-)",
    re.IGNORECASE,
)


def _looks_autogenerated(token: str | None) -> bool:
    if not token:
        return True
    return bool(_AUTOGEN_RE.search(token))


@dataclass
class ElementSpec:
    """Semantic, drift-resilient description of a target element.

    Captured once from a known-good element; used to re-find it later even
    after the page's ids/classes churn.
    """
    role: str | None = None
    name: str | None = None          # accessible name (role's name)
    label: str | None = None         # associated <label> text
    testid: str | None = None
    elem_id: str | None = None
    name_attr: str | None = None
    placeholder: str | None = None
    aria_label: str | None = None
    css_class_fragment: str | None = None
    text: str | None = None
    tag: str | None = None
    # Raw multi-signal fingerprint for the scored fallback (tier 10)
    fingerprint: dict[str, Any] = field(default_factory=dict)
    # Optional explicit fallback CSS selectors (hand-authored skills)
    css_fallbacks: list[str] = field(default_factory=list)


# Shared JS: a STRUCTURAL label resolver. The <label for=id> link is exactly
# what churns between ATS sessions, so we resolve the field's label by DOM
# proximity instead: for/id link → wrapping <label> → nearest preceding
# <label>/<legend> within the closest field container. This is the stable
# anchor the scored fallback leans on.
_NEAR_LABEL_FN = r"""
  const norm = s => (s || '').replace(/\s+/g, ' ').trim();
  function nearLabel(el) {
    if (el.id) {
      const L = document.querySelector('label[for="' + CSS.escape(el.id) + '"]');
      if (L) return norm(L.textContent);
    }
    const W = el.closest('label');
    if (W) return norm(W.textContent);
    const box = el.closest('div,fieldset,li,p,section') || el.parentElement;
    if (box) {
      const labels = box.querySelectorAll('label,legend');
      // nearest label that appears before the element in DOM order
      let best = '';
      for (const L of labels) {
        if (L.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING) {
          best = norm(L.textContent);
        }
      }
      if (best) return best;
      if (labels.length) return norm(labels[0].textContent);
    }
    let p = el.previousElementSibling;
    for (let i = 0; i < 3 && p; i++, p = p.previousElementSibling) {
      if (/^(label|legend|span|div|p)$/i.test(p.tagName) && norm(p.textContent))
        return norm(p.textContent);
    }
    return '';
  }
"""

_FINGERPRINT_JS = r"""
(el) => {
  %s
  const cs = el.getAttribute('class') || '';
  const r = el.getBoundingClientRect();
  return {""" % _NEAR_LABEL_FN + r"""
    tag: el.tagName.toLowerCase(),
    type: el.getAttribute('type') || '',
    role: el.getAttribute('role') || '',
    name_attr: el.getAttribute('name') || '',
    aria_label: el.getAttribute('aria-label') || '',
    placeholder: el.getAttribute('placeholder') || '',
    testid: el.getAttribute('data-testid') || el.getAttribute('data-test-id') || '',
    id: el.id || '',
    classes: cs,
    label_text: nearLabel(el),
    text: norm(el.textContent).slice(0, 80),
    x: Math.round(r.x), y: Math.round(r.y),
  };
}
"""


def capture_spec(locator: "Locator") -> ElementSpec:
    """Build an ElementSpec from a known-good, currently-resolving locator."""
    fp = locator.evaluate(_FINGERPRINT_JS)
    cls_frag = _stable_class_fragment(fp.get("classes", ""))
    return ElementSpec(
        role=fp.get("role") or _implicit_role(fp.get("tag", ""), fp.get("type", "")),
        name=fp.get("aria_label") or fp.get("label_text") or fp.get("text") or None,
        label=fp.get("label_text") or None,
        testid=fp.get("testid") or None,
        elem_id=None if _looks_autogenerated(fp.get("id")) else (fp.get("id") or None),
        name_attr=fp.get("name_attr") or None,
        placeholder=fp.get("placeholder") or None,
        aria_label=fp.get("aria_label") or None,
        css_class_fragment=cls_frag,
        text=fp.get("text") or None,
        tag=fp.get("tag") or None,
        fingerprint=fp,
    )


def _implicit_role(tag: str, typ: str) -> str | None:
    tag = (tag or "").lower()
    typ = (typ or "").lower()
    if tag == "button" or (tag == "input" and typ in ("button", "submit", "reset")):
        return "button"
    if tag == "a":
        return "link"
    if tag == "select":
        return "combobox"
    if tag == "textarea":
        return "textbox"
    if tag == "input" and typ in ("", "text", "email", "tel", "url", "search", "password"):
        return "textbox"
    if tag == "input" and typ == "checkbox":
        return "checkbox"
    if tag == "input" and typ == "radio":
        return "radio"
    return None


def _stable_class_fragment(classes: str) -> str | None:
    """Pick the most semantic, non-autogenerated class token."""
    toks = [c for c in (classes or "").split() if c and not _looks_autogenerated(c)]
    if not toks:
        return None
    # Prefer tokens that look semantic (contain a letter word ≥4 chars).
    toks.sort(key=lambda c: (-len(c), c))
    for t in toks:
        if re.search(r"[a-zA-Z]{4,}", t):
            return t
    return toks[0]


def _first_present(page: "Page", selector: str):
    try:
        loc = page.locator(selector).first
        if loc.count() > 0:
            return loc
    except Exception:
        return None
    return None


def heal(page: "Page", spec: ElementSpec, *, timeout_ms: int = 1000):
    """Re-find the element described by `spec`. Returns (Locator|None, tier).

    Walks the priority hierarchy; falls back to scored fingerprint
    re-discovery. Tier string is for telemetry ("role_name", "label",
    "testid", "id", "name_attr", "placeholder", "aria_label", "css_class",
    "text", "fingerprint", or "" if not found).
    """
    deadline = time.monotonic() + timeout_ms / 1000.0

    # 1. role + accessible name (most stable)
    if spec.role and spec.name:
        try:
            loc = page.get_by_role(spec.role, name=spec.name, exact=False).first
            if loc.count() > 0:
                return loc, "role_name"
        except Exception:
            pass
    # 2. label
    if spec.label:
        try:
            loc = page.get_by_label(spec.label, exact=False).first
            if loc.count() > 0:
                return loc, "label"
        except Exception:
            pass
    # 3. data-testid
    if spec.testid:
        loc = _first_present(page, f'[data-testid="{spec.testid}"], [data-test-id="{spec.testid}"]')
        if loc:
            return loc, "testid"
    # 4. stable id
    if spec.elem_id and not _looks_autogenerated(spec.elem_id):
        loc = _first_present(page, f'#{_css_escape(spec.elem_id)}')
        if loc:
            return loc, "id"
    # 5. name attribute
    if spec.name_attr:
        loc = _first_present(page, f'[name="{spec.name_attr}"]')
        if loc:
            return loc, "name_attr"
    # 6. placeholder
    if spec.placeholder:
        try:
            loc = page.get_by_placeholder(spec.placeholder, exact=False).first
            if loc.count() > 0:
                return loc, "placeholder"
        except Exception:
            pass
    # 7. aria-label
    if spec.aria_label:
        loc = _first_present(page, f'[aria-label="{spec.aria_label}"]')
        if loc:
            return loc, "aria_label"
    # 8. stable class fragment
    if spec.css_class_fragment:
        loc = _first_present(page, f'.{_css_escape(spec.css_class_fragment)}')
        if loc:
            return loc, "css_class"
    # 9. exact visible text
    if spec.text and len(spec.text) <= 80:
        try:
            loc = page.get_by_text(spec.text, exact=False).first
            if loc.count() > 0:
                return loc, "text"
        except Exception:
            pass
    # 10. scored fingerprint re-discovery
    if time.monotonic() < deadline:
        loc = _scored_rediscover(page, spec)
        if loc is not None:
            return loc, "fingerprint"
    return None, ""


def _css_escape(token: str) -> str:
    return re.sub(r'(["\\\]\[\.#:>~+()\s])', r"\\\1", token)


_SCORE_JS = r"""
(args) => {
  %s
  const fp = args.fp;
  const lc = s => (s || '').replace(/\s+/g, ' ').trim().toLowerCase();
  const tag = (fp.tag || 'input').toLowerCase();""" % _NEAR_LABEL_FN + r"""
  // Candidate pool: same tag (cheap, covers the vast majority of churn).
  const pool = Array.from(document.getElementsByTagName(tag || '*'));
  let best = null, bestScore = -1, bestIdx = -1;
  pool.forEach((el, idx) => {
    let s = 0, max = 0;
    // Only count a signal's weight toward `max` when the fingerprint
    // actually HAS that signal — so a churned page that stripped most
    // attributes isn't penalized for what the recorder never captured.
    const add = (w, a, b) => { if (!b) return; max += w; if (a && lc(a) === lc(b)) s += w; };
    const addInc = (w, a, b) => { if (!b) return; max += w; if (a && (lc(a).includes(lc(b)) || lc(b).includes(lc(a)))) s += w; };
    add(3, el.getAttribute('name'), fp.name_attr);
    add(3, el.getAttribute('data-testid') || el.getAttribute('data-test-id'), fp.testid);
    add(2, el.getAttribute('type'), fp.type);
    add(2, el.getAttribute('role'), fp.role);
    add(2, el.getAttribute('aria-label'), fp.aria_label);
    add(2, el.getAttribute('placeholder'), fp.placeholder);
    addInc(5, nearLabel(el), fp.label_text);   // structural label = strongest stable anchor
    addInc(2, el.textContent && el.textContent.slice(0,80), fp.text);
    // positional proximity (weak tie-breaker; always available)
    max += 1;
    try {
      const r = el.getBoundingClientRect();
      const d = Math.abs(r.x - fp.x) + Math.abs(r.y - fp.y);
      if (d < 60) s += 1; else if (d < 200) s += 0.5;
    } catch (e) {}
    const ratio = max > 0 ? s / max : 0;
    if (ratio > bestScore) { bestScore = ratio; best = el; bestIdx = idx; }
  });
  if (best && bestScore >= 0.6) {
    // UNIQUE per-call token. A shared "1" marker collided when several
    // fields healed via fingerprint in one pass (a churned form): every
    // call tagged "1", so `[data-applypilot-heal="1"]`.first returned the
    // FIRST stale-tagged element, mis-filling later fields. Tag with the
    // caller's token so locators never cross-collide.
    best.setAttribute('data-applypilot-heal', args.token);
    return {idx: bestIdx, score: bestScore, tag: tag};
  }
  return {idx: -1, score: bestScore};
}
"""

_heal_token_counter = 0


def _scored_rediscover(page: "Page", spec: ElementSpec):
    """Scan same-tag candidates, score each against the fingerprint, tag the
    winner with a UNIQUE token and return a locator to exactly that element."""
    global _heal_token_counter
    _heal_token_counter += 1
    token = f"h{_heal_token_counter}"
    try:
        res = page.evaluate(_SCORE_JS, {"fp": spec.fingerprint or {}, "token": token})
    except Exception:
        return None
    if not res or res.get("idx", -1) < 0:
        return None
    try:
        loc = page.locator(f'[data-applypilot-heal="{token}"]').first
        if loc.count() > 0:
            return loc
    except Exception:
        return None
    return None
